wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-w08_adaptive-and-unified-approach-to-risk-management-and-compliance-via-ccf_copy1.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w10b-anatomy-of-an-attack.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-r04_a-new-way-of-looking-at-smart-city-security-securing-the-fabric.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-r05_arm-a-security-opportunity-against-advanced-persistent-threats.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-w10-a-use-case-framework-for-intelligence-driven-security-operations-centers.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w06-badmin-abusing-legitimate-sysadmin-tools-for-offense.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cin-r06-becoming-the-adversary.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-w06_cloud-security-myths-and-reality.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cin-w10-combatting-cyber-risk-in-the-supply-chain_final.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-r04-cyber-security-awareness-for-executives.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-w08-cyber-threat-intelligence-sharing-standards.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-w10_escalating-middle-eastern-cyber-tension-an-open-source-_osint_-analysis_copy1.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-w10_escalating-middle-eastern-cyber-tension-an-open-source-_osint_-analysis.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-w08_evolving-threats-dissection-of-a-cyber-espionage-attack.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cin-w08-false-data-injection-attacks-on-industrial-control-systems.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cin-w09-from-fences-to-bodyguards-how-data-centric-security-works.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-w06_global-regional-trends-in-cybercrime-the-divergence-of-cybercriminals.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-r04-grc-implementation-behind-the-scenes.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-w07_how-i-learned-to-stop-worrying-and-love-the-internet-of-things.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w09b-how-next-generation-trusted-identities-can-help-transform-your-business.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-r05-how-to-prepare-for-the-worst-dont-let-your-first-crisis-be-a-real-one.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-w07-introducing-a-new-ciso-dos-and-donts-of-the-first-six-months.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-w09_iot-securing-the-smart-city.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-r05a-iot-the-next-byod_will-we-make-the-same-mistakes.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-r06_journey-into-the-darknet.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w08-let_s-go-hunting.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w10a-lie-cheat-and-deceive-change-the-rules-of-cyber-defense.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cin-w07-logically-securing-a-public-cloud-service.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-w09-machine-learning-the-new-face-of-byod.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-r05-maximum-overdrive-death-by-your-microwave.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-r06a-obtaining-enterprise-cyber-situational-awareness.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-w09-overcome-by-cyber-risks.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-r06-proactive-counterespionage-as-a-part-of-business-continuity-and-resiliency_with_white_paper.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-w09_protecting-the-energy-industrial-infrastructures-from-advancing-threats.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-r06_securing-automobility-cyborgs-and-the-social-network-of-things.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-w10_securing-smart-city-platforms-iot-m2m-cloud-and-big-data.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sem-t01_security-basics_seminar.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cin-r04-security_intelligence_the_truth_is_out_there_copy1.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-w07-security-posture-for-critical-information-infrastructure-protection-_ciip__copy1.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/ssc-w08_smart-grid-security-a-look-to-the-future.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-r05-state-of-the-art-in-strategic-decision-making-exercises-in-cyber-security.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-w06-the-components-of-national-and-international-governance-of-cyberspace.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-r05b-the-real-security-issues-that-deserve-a-logo.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/sop-w06-ticking-time-bomb-of-insider-threat.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-r04-the-time-is-now_a-new-era-for-cybersecurity.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-r06-the-zerotrust-initiative_there-is-no-security-without-transparency.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cct-r04_understanding-cyber-attacks-that-leverage-the-telephony-channel.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/cin-w06-using-security-analytics-to-transform-smart-grid-security_copy1.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w07b-using-visibility-to-turn-the-tables-on-cybercriminals_v4.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/pst-w10-whose-cloud-is-it-anyway.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w07a-why-the-global-cyber-security-landscape-paints-a-concerning-picture.pdf
wget -c http://www.rsaconference.com//writable/presentations/file_upload/spo-w09a-windows-10-disrupting-cyber-threats.pdf
